technologiestiftung/citylab-microsite

- pages/events/_event.vue
Reverts technologiestiftung/citylab-microsite#53
> Revert "fix: event meta tags"

- assets/content/smartcity.js
> EN translation

- assets/content/smartcity.js
Add pdf submission to list of buttons
> add submission to list of downloads

- assets/content/smartcity.js
- pages/smart_city.vue
- pages/smart_city_en.vue
++ added same svg icon in the download buttons
++ left align
++ width 100% instead of 250px for better responsiveness
> left align & pdf icon for buttons

- pages/projects_en/_project.vue
Please create your PR against the staging branch. Not master!
fixes the link button on EN projects page appearing all the time instead of only when needed
> link button fix

- assets/content/jobs.js
- pages/jobs_en.vue
++ added job position to jobs.js
++ added logic for DE/EN download links to jobs_en.vue
> job offer added

- assets/content/jobs.js
Adds the new Service Designer listing to our jobs page
> Add Service Designer Job Posting

- assets/content/jobs.js
For consistency, changed the German job descriptions to solely use * to indicate inclusivity for all gender.
> minor edit: replace : with *

- pages/all_events.vue
- pages/all_events_en.vue
> add 2021 to events overview

- assets/content/jobs.js
-- removed full stack dev position from job page
> removed Dull Stack Developer Position

- pages/all_events.vue
- pages/all_events_en.vue
> chore(CLAB-12): display 2021 events by default

- assets/content/jobs.js
This posting should no longer be live on the CityLAB website.
> Removes Service Designer job posting

- components/Newsletter.vue
- pages/newsletter_archive.vue
- pages/newsletter_archive_en.vue
This PR adds the newsletter signup form to the News page.
> feat(CLAB-16): newsletter signup

- components/Footer.vue
> fix: attempt to solve CSS specificity issue

- assets/content/jobs.js
> chore: remove job opening (Community management)

- components/Navigation.vue
For small viewport heights.
Fix positioning, z-index, backgrounds etc.
> fix(nav): make nav visually accessible

- assets/content/smartcity.js
> chore: update Smart City participation text

- assets/content.js
> fix: attempt to make Symposium visible in events table

- pages/events/smart-city-symposium-en.vue
- pages/events/smart-city-symposium.vue
> fix: make anchor links visible

- assets/content/smartcity.js
English body texts yet to follow
> feat: update Smart City timeline

- assets/content/smartcity.js
> chore: update Smart City commenting date

- components/Projects.vue
> fix: always load project tile images from root

- assets/content/jobs.js
> fix: job openings

- assets/content/jobs.js
> chore: add new job opening

- README.md
This PR updates the docs so that the removal of the Google Spreadsheet is documented in the README and instructions are given for creating/updating events, projects etc.
> docs: change from spreadsheet to JSON files [skip ci]
